### ISSUE TITLE
AttributeError: module 'absl' has no attribute 'flags'

### ISSUE THREAD

**Issue by sehargul-123** [abseil/abseil-py#119]
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/logging.py", line 6, in <module>
    from util.flags import FLAGS
  File "/home/sehar/DeepSpeech/util/flags.py", line 6, in <module>
    FLAGS = absl.flags.FLAGS
AttributeError: module 'absl' has no attribute 'flags'
please help me resolve this issue I am using tensorflow 1.14 gpu based

**Comment by yilei** [comment]
This isn't a `absl` specific issue, but:

Note that `import logging` tries to import `/home/sehar/DeepSpeech/logging.py`, instead of Python's standard [`logging` module](https://docs.python.org/library/logging.html)

You likely have `''` in your `sys.path` before the standard modules, and `/home/sehar/DeepSpeech/` is your current directory. Can you rename `/home/sehar/DeepSpeech/logging.py` to something else?

**Comment by sehargul-123** [comment]
i am not getting you please can you explain me in detail

**Comment by sehargul-123** [comment]
I am not getting you please can you explain me in detail

**Comment by sehargul-123** [comment]
how can I rename it to something else??

**Comment by sehargul-123** [comment]
what should I rename it?? can u give me a name as an example

**Comment by sehargul-123** [comment]
i am not getting you please can you tell me what name should i give as an example

**Comment by sehargul-123** [comment]
will u reply please

**Comment by yilei** [comment]
Looks like you are using `https://github.com/mozilla/DeepSpeech`?

I checked DeepSpeech's code, `/home/sehar/DeepSpeech/logging.py` seems to match `https://github.com/mozilla/DeepSpeech/blob/master/util/logging.py`, but the file is located inside the `util` directory.

I'm not sure where `/home/sehar/DeepSpeech/logging.py` comes from, do you have `/home/sehar/DeepSpeech/util/logging.py` exists? What if you remove `/home/sehar/DeepSpeech/logging.py`, or move the file to the `util` directory?

What if you delete `/home/sehar/DeepSpeech` and re-install it?

**Comment by yilei** [comment]
Closing due to inactivity. Feel free to re-open if you have more questions.

**Comment by incupadAftab** [comment]
Try the 'sudo python -m pip install absl-py'  instead of pip installed absl-py.
